services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile

    depends_on:
      - db

    ports:
      - "8080:8080"

    volumes:
      - ./backend/:/app

    restart: unless-stopped
    environment:
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile

    ports:
      - "5173:5173"

    volumes:
      - ./frontend/:/app

    restart: unless-stopped

  db:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-app_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
