"""remove fingerprint from session

Revision ID: 91e13626cf1b
Revises: 2c597bfa5121
Create Date: 2026-08-26 15:51:48.758240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "91e13626cf1b"
down_revision: Union[str, Sequence[str], None] = "2c597bfa5121"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_sessions", "fingerprint")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_sessions",
        sa.Column(
            "fingerprint",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
            server_default="",
        ),
    )
    op.alter_column("refresh_sessions", "fingerprint", server_default=None)
    # ### end Alembic commands ###
